name: internship_practice
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_slidable: ^2.0.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  intl: ^0.17.0
  firebase_messaging: ^14.4.1
  http: ^0.13.5
  flutter_local_notifications: ^14.0.0
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  full_screen_image: ^2.0.0
  timeago: ^3.0.0
  connectivity_plus: ^3.0.0
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  shimmer: ^2.0.0
  giphy_get: ^3.0.0
  uuid: ^3.0.7
  agora_rtc_engine: ^6.1.1+1
  agora_uikit: ^1.0.2
  permission_handler: ^10.2.0
  video_player: ^2.6.1
  record: ^4.4.4
  audioplayers: ^4.0.1
  chewie: ^1.5.0
  auto_route: ^4.0.0
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.2
  mockito: ^5.3.0

flutter:


  uses-material-design: true


  assets:
    - .env
    - assets/images/



