// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADX9sThnlwu7T3jSw0Ns_QkJFAjUvxFwI',
    appId: '1:510004784938:web:b05776fef816ccf7687853',
    messagingSenderId: '510004784938',
    projectId: 'bloc-practice-c9106',
    authDomain: 'bloc-practice-c9106.firebaseapp.com',
    storageBucket: 'bloc-practice-c9106.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vzPJBMalQPYOGgU48CElPKjgZsk-sGA',
    appId: '1:510004784938:android:6c3acaeccdc7cd0f687853',
    messagingSenderId: '510004784938',
    projectId: 'bloc-practice-c9106',
    storageBucket: 'bloc-practice-c9106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnTXfCgmVouPio9Ipt7MvhoAdBxtEQdTc',
    appId: '1:510004784938:ios:26d0184fe7e8d84b687853',
    messagingSenderId: '510004784938',
    projectId: 'bloc-practice-c9106',
    storageBucket: 'bloc-practice-c9106.appspot.com',
    androidClientId: '510004784938-t0l47jnipn73ban8ug8hhunr3m9qsnej.apps.googleusercontent.com',
    iosClientId: '510004784938-ic2ddlrtlimah7kv92oh5hjk6234rsuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnTXfCgmVouPio9Ipt7MvhoAdBxtEQdTc',
    appId: '1:510004784938:ios:26d0184fe7e8d84b687853',
    messagingSenderId: '510004784938',
    projectId: 'bloc-practice-c9106',
    storageBucket: 'bloc-practice-c9106.appspot.com',
    androidClientId: '510004784938-t0l47jnipn73ban8ug8hhunr3m9qsnej.apps.googleusercontent.com',
    iosClientId: '510004784938-ic2ddlrtlimah7kv92oh5hjk6234rsuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipPractice',
  );
}
